image: niharkapadia/pipelines-kubectl:latest

pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: Deploy DIH to Kubernetes ..
        deployment: test
        script:
          - cd smart-dih-demo
          - mvn clean package -DskipTests
          - aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile default && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default && aws configure set region "us-east-2" --profile default && aws configure set output "json" --profile default
          - aws s3 cp --acl public-read-write target/smart-dih-demo-1.0-SNAPSHOT.jar s3://aa-nihar-test/Bitbucket-demo/
          - aws eks update-kubeconfig --region us-east-2 --name dih-lab
          - helm repo add gigaspaces https://resources.gigaspaces.com/helm-charts
          - helm repo update
          - helm upgrade -i manager gigaspaces/xap-manager --version 16.0
          - helm upgrade -i demo gigaspaces/xap-pu --version 16.0 --set manager.name=manager,partitions=2
          - helm upgrade -i feeder gigaspaces/xap-pu --version 16.0 --set manager.name=manager,resourceUrl="https://aa-nihar-test.s3.us-east-2.amazonaws.com/Bitbucket-demo/smart-dih-demo-1.0-SNAPSHOT.jar"