apiVersion: v1
kind: Service
metadata:
  name: my-rest-api
  namespace: smartcache
  labels:
    app: my-rest-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-rest-api
